spring:
  datasource:
    url: jdbc:mysql://172.30.1.91:3301/payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: payment
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true